

* Адмиралтейский отдел ЗАГС

Адрес: Санкт-Петербург, 1-ая Красноармейская ул., д. 6

Телефон: (812) 316-05-29

Метро: Технологический институт

Время работы: вт. - пт. 9.30 - 17.30 перерыв: 13.00 - 14.00 ,прием начальника отдела: вт. 14.00 - 17.00 чт. 10.00 - 13.00

В Санкт-Петербурге на 1 Красноармейской улице стоит небольшое трёхэтажное здание, построенное в 30-е годы XX века.

* Василеостровский отдел ЗАГС
Адрес: Санкт-Петербург, Капитанская ул., д.4

Телефон: (812) 305-57-92, 305-57-91, 305-57-93

Метро: Приморская

Время работы: вторник - суббота 09.30-17.00, выходные дни - воскресенье, понедельник. Торжественная регистрация брака по субботам 10.00-16.00

* Выборгский отдел ЗАГС
Адрес: Санкт-Петербург, Институтский пр., д. 8

Телефон: (812) 550-24-27, 550-24-28, 550-44-02

Метро: Площадь Мужества

Время работы: вторник - суббота,09.30-17.30 (в субботу до 13.00), обед 13.00-14.00, выходные дни - воскресенье, понедельник.

* Дворец бракосочетания № 1
Адрес: Санкт-Петербург, Английская набережная, д. 28/1

Телефон: (812) 314-98-48

Метро: Невский Проспект

Время работы: 10.00-19.00

* Дворец бракосочетания № 2
Адрес: Санкт-Петербург, Фурштатская ул., д. 52

Телефон: (812) 273-73-96

Метро: Чернышевская

Время работы: Ежедневно 10.00 - 19:00, пн. 10:00 - 18:00

Дворец бракосочетания №2 открыт 10 февраля 1963 года.

* Дворец регистрации Малютка
Адрес: Санкт-петербуг, Фурштатская ул, д.58

Телефон: 272-83-78

Время работы: Прием заявлений: ежедневно 10.00 -18.00; обед 14.00 - 15.00, сб., 10.00-14.00;

* ЗАГС Курортного района
Адрес: Зеленогорск, проспект Ленина,14

Телефон: (495) 160-26-83

Время работы: Пн-Пт, 9.30-17.30; Сб,9.30-16.30, обед 13-14;

* ЗАГС Фрунзенского района
Адрес: Санкт-Петербург, пр.Славы, д.31

Телефон: (812)701-88-88 , 701-88-77

Время работы: вторник - суббота 09.30-17.30 (в субботу до 13.00), обед 13.00-14.00, выходные дни - воскресенье, понедельник.

* Калининский отдел ЗАГС
Адрес: Санкт-Петербург, Арсенальная наб., д. 13, к. 1

Телефон: (812)542-31-07 , 542-03-08

Метро: Площадь Ленина

Время работы: вт. - пт. 9.30 - 17.30 перерыв: 13.00 - 14.00 ,сб., 9.30-13.00

* Кировский отдел ЗАГС
Адрес: Санкт-Петербург, пр. Стачек, д. 45

Телефон: (812)786-40-80

Метро: Кировский завод

Время работы: вторник - суббота 09.30-17.30 (в субботу до 13.00), обед 13.00-14.00, выходные дни - воскресенье, понедельник.

* Колпинский отдел ЗАГС
Адрес: Колпино, Тверская ул., д. 1/13

Телефон: (812) 463-32-33, 463-48-3

Время работы: вторник - суббота с 09.30-17.30 (в субботу до 16.30), обед 13.00-14.00, выходные дни - воскресенье, понедельник.

* Красногвардейский отдел ЗАГС
Адрес: Санкт-Петербург, Большеохтинский пр., д. 11

Телефон: (812) 224-18-96, 224-23-06

Время работы: вторник - суббота 09.30-17.30 (в субботу до 13.00), обед 13.00-14.00, выходные дни - воскресенье, понедельник.

* Красносельский отдел ЗАГС
Адрес: Санкт-Петербург, пр. Ветеранов, д. 131

Телефон: (812) 736-68-15, 736-89-95, 736-68-24

Время работы: вторник - суббота 09.30-17.30 (в субботу до 13.00), обед 13.00-14.00, выходные дни - воскресенье, понедельник.

* Кронштадтский загс
Адрес: г. Кронштадт, пр. Ленина, 32

Телефон: 311 21 21

Время работы: вторник - пятница – с 9-30 до 17-30, суббота – с 9-30 до 16-30; перерыв: с 13-00 до 14-00;

Прием начальника отдела: вторник – с 14-00 до 17-00, четверг – с 10-00 до 13-00, санитарный день – последний рабочий день месяца.

* Курортный отдел ЗАГС
Адрес: Сестрорецк, пл. Свободы, д. 1

Телефон: (812) 437-29-94

Время работы: Пн-Пт, 9.30-17.30; Сб,9.30-16.30, обед 13-14;

* Ломоносовский отдел ЗАГС
Адрес: Ломоносов, Владимирская ул., д. 19/15

Телефон: (812) 423-36-91‎

Время работы: Пн-чт, 09.00-16; Обед 13.00-14.00

* Московский отдел ЗАГС
Адрес: Санкт-Петербург, Московский пр., д. 194

Телефон: (812) 388-04-49, 388-09-74

Время работы: вторник - суббота, 09.30-17.30 (в субботу до 13.00), обед 13.00-14.00, выходные дни - воскресенье, понедельник.

* Невский отдел ЗАГС
Адрес: Санкт-Петербург, Народная ул., д. 2

Телефон: (812) 446-84-80, 263-84-80, 447-21-78

Время работы: вторник - суббота 09.30-17.30 (в субботу до 13.00), обед 13.00-14.00, выходные дни - воскресенье, понедельник.

* Отдел ЗАГС г. Кронштадта
Адрес: Кронштадт, пр. Ленина, д. 32

Телефон: (812) 236-21-21

Время работы: вторник - суббота 09.30-17.30 (в субботу до 13.00), обед 13.00-14.00, выходные дни - воскресенье, понедельник.

* Отдел ЗАГС г. Ломоносова
Адрес: Ломоносов, пр. Дворцовый, д. 40

Телефон: (812) 422-94-88

Отдел ЗАГС г. Павловска

Адрес: Павловск, ул. Розы Люксембург, д. 11/16, к. 18

Телефон: (812) 470-90-69, 470-69-14

* Петроградский отдел ЗАГС
Адрес: Санкт-Петербург, Большая Монетная ул., д. 17

Телефон: (812) 232-73-39, 232-87-75

Метро: Петроградская

Время работы: вторник - суббота 09.30-17.30 (в субботу до 13.00), обед 13.00-14.00, выходные дни - воскресенье, понедельник.

* Петродворцовский отдел ЗАГС
Адрес: Санкт-Петербург, Петербургский пр., д.11/4

Телефон: (812) 427-50-23, 450-50-23

Время работы: вторник - суббота 09.30-17.30 (в субботу до 13.00), обед 13.00-14.00, выходные дни - воскресенье, понедельник.

* Приморский отдел ЗАГС
Адрес: Санкт-Петербург, аллея Котельникова, д. 2а

Телефон: (812) 301-01-15, 301-01-10

Время работы: вторник - суббота 09.30-17.30 (в субботу до 13.00), обед 13.00-14.00, выходные дни - воскресенье, понедельник.

* Пушкинский отдел ЗАГС
Адрес: Пушкин, Церковная ул., д. 2/4

Телефон: (812) 466-60-84, 466-24-11

Время работы: вторник - суббота,09.30-17.30 (в субботу до 13.00), обед 13.00-14.00, выходные дни - воскресенье, понедельник.

* Управление ЗАГС правительства ЛО
Адрес: Санкт-Петербург, Суворовский пр., д. 67

Телефон: (812) 274-64-28

* Фрунзенский загс
Адрес: пр. Славы, 31

Телефон: 701 88 87, 701 88 88, 701 88 77

Вторник- пятница – с 9-30 до 17-30; суббота – с 9-30 до 13-00; перерыв: с 13-00 до 14-00; санитарный день – последний рабочий день месяца.

* Центральный отдел ЗАГС
Адрес: Санкт-Петербург, Суворовский пр., д. 41

Телефон: (812) 275-78-74
